# Generated by Django 4.2.4 on 2023-08-08 06:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=130)),
                ('user_email', models.CharField(max_length=30)),
                ('user_balance', models.BigIntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myApp.user')),
                ('user_flags', models.JSONField(default=dict)),
            ],
        ),
    ]
